target: mGPT.archs.mgpt_mbart.Mbart_Based_MLM
params:
  model_type: mbart_multi
  model_path: ./deps/mbart-h2s-csl-phoenix
  num_heads: 3
  stage: ${TRAIN.STAGE}
  motion_codebook_size: ${model.params.codebook_size}
  ablation: ${ABLATION}
  use_kws: ${oc.select:KWS.ENABLED,false}
  name2kws_path: ${oc.select:KWS.NAME2KWS_PATH,scripts/name2kws_{split}.json}
  word2code_path: ${oc.select:KWS.WORD2CODE_PATH,scripts/word2code.json}
  debug_kws: ${oc.select:KWS.DEBUG,false}
